// deno-lint-ignore-file
// deno-fmt-ignore-file

// Generated by Snowball 2.2.0 - https://snowballstem.org/

import { BaseStemmer } from "./base-stemmer.js";

/**@constructor*/
export var Lovins = function () {
  var base = new BaseStemmer();
  /** @const */ var a_0 = [
    ["d", -1, -1],
    ["f", -1, -1],
    ["ph", -1, -1],
    ["th", -1, -1],
    ["l", -1, -1],
    ["er", -1, -1],
    ["or", -1, -1],
    ["es", -1, -1],
    ["t", -1, -1],
  ];

  /** @const */ var a_1 = [
    ["s'", -1, 1, r_A],
    ["a", -1, 1, r_A],
    ["ia", 1, 1, r_A],
    ["ata", 1, 1, r_A],
    ["ic", -1, 1, r_A],
    ["aic", 4, 1, r_A],
    ["allic", 4, 1, r_BB],
    ["aric", 4, 1, r_A],
    ["atic", 4, 1, r_B],
    ["itic", 4, 1, r_H],
    ["antic", 4, 1, r_C],
    ["istic", 4, 1, r_A],
    ["alistic", 11, 1, r_B],
    ["aristic", 11, 1, r_A],
    ["ivistic", 11, 1, r_A],
    ["ed", -1, 1, r_E],
    ["anced", 15, 1, r_B],
    ["enced", 15, 1, r_A],
    ["ished", 15, 1, r_A],
    ["ied", 15, 1, r_A],
    ["ened", 15, 1, r_E],
    ["ioned", 15, 1, r_A],
    ["ated", 15, 1, r_I],
    ["ented", 15, 1, r_C],
    ["ized", 15, 1, r_F],
    ["arized", 24, 1, r_A],
    ["oid", -1, 1, r_A],
    ["aroid", 26, 1, r_A],
    ["hood", -1, 1, r_A],
    ["ehood", 28, 1, r_A],
    ["ihood", 28, 1, r_A],
    ["elihood", 30, 1, r_E],
    ["ward", -1, 1, r_A],
    ["e", -1, 1, r_A],
    ["ae", 33, 1, r_A],
    ["ance", 33, 1, r_B],
    ["icance", 35, 1, r_A],
    ["ence", 33, 1, r_A],
    ["ide", 33, 1, r_L],
    ["icide", 38, 1, r_A],
    ["otide", 38, 1, r_A],
    ["age", 33, 1, r_B],
    ["able", 33, 1, r_A],
    ["atable", 42, 1, r_A],
    ["izable", 42, 1, r_E],
    ["arizable", 44, 1, r_A],
    ["ible", 33, 1, r_A],
    ["encible", 46, 1, r_A],
    ["ene", 33, 1, r_E],
    ["ine", 33, 1, r_M],
    ["idine", 49, 1, r_I],
    ["one", 33, 1, r_R],
    ["ature", 33, 1, r_E],
    ["eature", 52, 1, r_Z],
    ["ese", 33, 1, r_A],
    ["wise", 33, 1, r_A],
    ["ate", 33, 1, r_A],
    ["entiate", 56, 1, r_A],
    ["inate", 56, 1, r_A],
    ["ionate", 56, 1, r_D],
    ["ite", 33, 1, r_AA],
    ["ive", 33, 1, r_A],
    ["ative", 61, 1, r_A],
    ["ize", 33, 1, r_F],
    ["alize", 63, 1, r_A],
    ["icalize", 64, 1, r_A],
    ["ialize", 64, 1, r_A],
    ["entialize", 66, 1, r_A],
    ["ionalize", 64, 1, r_A],
    ["arize", 63, 1, r_A],
    ["ing", -1, 1, r_N],
    ["ancing", 70, 1, r_B],
    ["encing", 70, 1, r_A],
    ["aging", 70, 1, r_B],
    ["ening", 70, 1, r_E],
    ["ioning", 70, 1, r_A],
    ["ating", 70, 1, r_I],
    ["enting", 70, 1, r_C],
    ["ying", 70, 1, r_B],
    ["izing", 70, 1, r_F],
    ["arizing", 79, 1, r_A],
    ["ish", -1, 1, r_C],
    ["yish", 81, 1, r_A],
    ["i", -1, 1, r_A],
    ["al", -1, 1, r_BB],
    ["ical", 84, 1, r_A],
    ["aical", 85, 1, r_A],
    ["istical", 85, 1, r_A],
    ["oidal", 84, 1, r_A],
    ["eal", 84, 1, r_Y],
    ["ial", 84, 1, r_A],
    ["ancial", 90, 1, r_A],
    ["arial", 90, 1, r_A],
    ["ential", 90, 1, r_A],
    ["ional", 84, 1, r_A],
    ["ational", 94, 1, r_B],
    ["izational", 95, 1, r_A],
    ["ental", 84, 1, r_A],
    ["ful", -1, 1, r_A],
    ["eful", 98, 1, r_A],
    ["iful", 98, 1, r_A],
    ["yl", -1, 1, r_R],
    ["ism", -1, 1, r_B],
    ["icism", 102, 1, r_A],
    ["oidism", 102, 1, r_A],
    ["alism", 102, 1, r_B],
    ["icalism", 105, 1, r_A],
    ["ionalism", 105, 1, r_A],
    ["inism", 102, 1, r_J],
    ["ativism", 102, 1, r_A],
    ["um", -1, 1, r_U],
    ["ium", 110, 1, r_A],
    ["ian", -1, 1, r_A],
    ["ician", 112, 1, r_A],
    ["en", -1, 1, r_F],
    ["ogen", 114, 1, r_A],
    ["on", -1, 1, r_S],
    ["ion", 116, 1, r_Q],
    ["ation", 117, 1, r_B],
    ["ication", 118, 1, r_G],
    ["entiation", 118, 1, r_A],
    ["ination", 118, 1, r_A],
    ["isation", 118, 1, r_A],
    ["arisation", 122, 1, r_A],
    ["entation", 118, 1, r_A],
    ["ization", 118, 1, r_F],
    ["arization", 125, 1, r_A],
    ["action", 117, 1, r_G],
    ["o", -1, 1, r_A],
    ["ar", -1, 1, r_X],
    ["ear", 129, 1, r_Y],
    ["ier", -1, 1, r_A],
    ["ariser", -1, 1, r_A],
    ["izer", -1, 1, r_F],
    ["arizer", 133, 1, r_A],
    ["or", -1, 1, r_T],
    ["ator", 135, 1, r_A],
    ["s", -1, 1, r_W],
    ["'s", 137, 1, r_A],
    ["as", 137, 1, r_B],
    ["ics", 137, 1, r_A],
    ["istics", 140, 1, r_A],
    ["es", 137, 1, r_E],
    ["ances", 142, 1, r_B],
    ["ences", 142, 1, r_A],
    ["ides", 142, 1, r_L],
    ["oides", 145, 1, r_A],
    ["ages", 142, 1, r_B],
    ["ies", 142, 1, r_P],
    ["acies", 148, 1, r_A],
    ["ancies", 148, 1, r_A],
    ["encies", 148, 1, r_A],
    ["aries", 148, 1, r_A],
    ["ities", 148, 1, r_A],
    ["alities", 153, 1, r_A],
    ["ivities", 153, 1, r_A],
    ["ines", 142, 1, r_M],
    ["nesses", 142, 1, r_A],
    ["ates", 142, 1, r_A],
    ["atives", 142, 1, r_A],
    ["ings", 137, 1, r_N],
    ["is", 137, 1, r_A],
    ["als", 137, 1, r_BB],
    ["ials", 162, 1, r_A],
    ["entials", 163, 1, r_A],
    ["ionals", 162, 1, r_A],
    ["isms", 137, 1, r_B],
    ["ians", 137, 1, r_A],
    ["icians", 167, 1, r_A],
    ["ions", 137, 1, r_B],
    ["ations", 169, 1, r_B],
    ["arisations", 170, 1, r_A],
    ["entations", 170, 1, r_A],
    ["izations", 170, 1, r_A],
    ["arizations", 173, 1, r_A],
    ["ars", 137, 1, r_O],
    ["iers", 137, 1, r_A],
    ["izers", 137, 1, r_F],
    ["ators", 137, 1, r_A],
    ["less", 137, 1, r_A],
    ["eless", 179, 1, r_A],
    ["ness", 137, 1, r_A],
    ["eness", 181, 1, r_E],
    ["ableness", 182, 1, r_A],
    ["eableness", 183, 1, r_E],
    ["ibleness", 182, 1, r_A],
    ["ateness", 182, 1, r_A],
    ["iteness", 182, 1, r_A],
    ["iveness", 182, 1, r_A],
    ["ativeness", 188, 1, r_A],
    ["ingness", 181, 1, r_A],
    ["ishness", 181, 1, r_A],
    ["iness", 181, 1, r_A],
    ["ariness", 192, 1, r_E],
    ["alness", 181, 1, r_A],
    ["icalness", 194, 1, r_A],
    ["antialness", 194, 1, r_A],
    ["entialness", 194, 1, r_A],
    ["ionalness", 194, 1, r_A],
    ["fulness", 181, 1, r_A],
    ["lessness", 181, 1, r_A],
    ["ousness", 181, 1, r_A],
    ["eousness", 201, 1, r_A],
    ["iousness", 201, 1, r_A],
    ["itousness", 201, 1, r_A],
    ["entness", 181, 1, r_A],
    ["ants", 137, 1, r_B],
    ["ists", 137, 1, r_A],
    ["icists", 207, 1, r_A],
    ["us", 137, 1, r_V],
    ["ous", 209, 1, r_A],
    ["eous", 210, 1, r_A],
    ["aceous", 211, 1, r_A],
    ["antaneous", 211, 1, r_A],
    ["ious", 210, 1, r_A],
    ["acious", 214, 1, r_B],
    ["itous", 210, 1, r_A],
    ["ant", -1, 1, r_B],
    ["icant", 217, 1, r_A],
    ["ent", -1, 1, r_C],
    ["ement", 219, 1, r_A],
    ["izement", 220, 1, r_A],
    ["ist", -1, 1, r_A],
    ["icist", 222, 1, r_A],
    ["alist", 222, 1, r_A],
    ["icalist", 224, 1, r_A],
    ["ialist", 224, 1, r_A],
    ["ionist", 222, 1, r_A],
    ["entist", 222, 1, r_A],
    ["y", -1, 1, r_B],
    ["acy", 229, 1, r_A],
    ["ancy", 229, 1, r_B],
    ["ency", 229, 1, r_A],
    ["ly", 229, 1, r_B],
    ["ealy", 233, 1, r_Y],
    ["ably", 233, 1, r_A],
    ["ibly", 233, 1, r_A],
    ["edly", 233, 1, r_E],
    ["iedly", 237, 1, r_A],
    ["ely", 233, 1, r_E],
    ["ately", 239, 1, r_A],
    ["ively", 239, 1, r_A],
    ["atively", 241, 1, r_A],
    ["ingly", 233, 1, r_B],
    ["atingly", 243, 1, r_A],
    ["ily", 233, 1, r_A],
    ["lily", 245, 1, r_A],
    ["arily", 245, 1, r_A],
    ["ally", 233, 1, r_B],
    ["ically", 248, 1, r_A],
    ["aically", 249, 1, r_A],
    ["allically", 249, 1, r_C],
    ["istically", 249, 1, r_A],
    ["alistically", 252, 1, r_B],
    ["oidally", 248, 1, r_A],
    ["ially", 248, 1, r_A],
    ["entially", 255, 1, r_A],
    ["ionally", 248, 1, r_A],
    ["ationally", 257, 1, r_B],
    ["izationally", 258, 1, r_B],
    ["entally", 248, 1, r_A],
    ["fully", 233, 1, r_A],
    ["efully", 261, 1, r_A],
    ["ifully", 261, 1, r_A],
    ["enly", 233, 1, r_E],
    ["arly", 233, 1, r_K],
    ["early", 265, 1, r_Y],
    ["lessly", 233, 1, r_A],
    ["ously", 233, 1, r_A],
    ["eously", 268, 1, r_A],
    ["iously", 268, 1, r_A],
    ["ently", 233, 1, r_A],
    ["ary", 229, 1, r_F],
    ["ery", 229, 1, r_E],
    ["icianry", 229, 1, r_A],
    ["atory", 229, 1, r_A],
    ["ity", 229, 1, r_A],
    ["acity", 276, 1, r_A],
    ["icity", 276, 1, r_A],
    ["eity", 276, 1, r_A],
    ["ality", 276, 1, r_A],
    ["icality", 280, 1, r_A],
    ["iality", 280, 1, r_A],
    ["antiality", 282, 1, r_A],
    ["entiality", 282, 1, r_A],
    ["ionality", 280, 1, r_A],
    ["elity", 276, 1, r_A],
    ["ability", 276, 1, r_A],
    ["izability", 287, 1, r_A],
    ["arizability", 288, 1, r_A],
    ["ibility", 276, 1, r_A],
    ["inity", 276, 1, r_CC],
    ["arity", 276, 1, r_B],
    ["ivity", 276, 1, r_A],
  ];

  /** @const */ var a_2 = [
    ["bb", -1, -1],
    ["dd", -1, -1],
    ["gg", -1, -1],
    ["ll", -1, -1],
    ["mm", -1, -1],
    ["nn", -1, -1],
    ["pp", -1, -1],
    ["rr", -1, -1],
    ["ss", -1, -1],
    ["tt", -1, -1],
  ];

  /** @const */ var a_3 = [
    ["uad", -1, 18],
    ["vad", -1, 19],
    ["cid", -1, 20],
    ["lid", -1, 21],
    ["erid", -1, 22],
    ["pand", -1, 23],
    ["end", -1, 24],
    ["ond", -1, 25],
    ["lud", -1, 26],
    ["rud", -1, 27],
    ["ul", -1, 9],
    ["her", -1, 28],
    ["metr", -1, 7],
    ["istr", -1, 6],
    ["urs", -1, 5],
    ["uct", -1, 2],
    ["et", -1, 32],
    ["mit", -1, 29],
    ["ent", -1, 30],
    ["umpt", -1, 3],
    ["rpt", -1, 4],
    ["ert", -1, 31],
    ["yt", -1, 33],
    ["iev", -1, 1],
    ["olv", -1, 8],
    ["ax", -1, 14],
    ["ex", -1, 15],
    ["bex", 26, 10],
    ["dex", 26, 11],
    ["pex", 26, 12],
    ["tex", 26, 13],
    ["ix", -1, 16],
    ["lux", -1, 17],
    ["yz", -1, 33],
  ];

  /** @return {boolean} */
  function r_A() {
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    return true;
  }

  /** @return {boolean} */
  function r_B() {
    {
      var /** number */ c1 = base.cursor - 3;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    return true;
  }

  /** @return {boolean} */
  function r_C() {
    {
      var /** number */ c1 = base.cursor - 4;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    return true;
  }

  /** @return {boolean} */
  function r_D() {
    {
      var /** number */ c1 = base.cursor - 5;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    return true;
  }

  /** @return {boolean} */
  function r_E() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    {
      var /** number */ v_2 = base.limit - base.cursor;
      lab0: {
        if (!base.eq_s_b("e")) {
          break lab0;
        }
        return false;
      }
      base.cursor = base.limit - v_2;
    }
    return true;
  }

  /** @return {boolean} */
  function r_F() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 3;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    {
      var /** number */ v_2 = base.limit - base.cursor;
      lab0: {
        if (!base.eq_s_b("e")) {
          break lab0;
        }
        return false;
      }
      base.cursor = base.limit - v_2;
    }
    return true;
  }

  /** @return {boolean} */
  function r_G() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 3;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    if (!base.eq_s_b("f")) {
      return false;
    }
    return true;
  }

  /** @return {boolean} */
  function r_H() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    lab0: {
      var /** number */ v_2 = base.limit - base.cursor;
      lab1: {
        if (!base.eq_s_b("t")) {
          break lab1;
        }
        break lab0;
      }
      base.cursor = base.limit - v_2;
      if (!base.eq_s_b("ll")) {
        return false;
      }
    }
    return true;
  }

  /** @return {boolean} */
  function r_I() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    {
      var /** number */ v_2 = base.limit - base.cursor;
      lab0: {
        if (!base.eq_s_b("o")) {
          break lab0;
        }
        return false;
      }
      base.cursor = base.limit - v_2;
    }
    {
      var /** number */ v_3 = base.limit - base.cursor;
      lab1: {
        if (!base.eq_s_b("e")) {
          break lab1;
        }
        return false;
      }
      base.cursor = base.limit - v_3;
    }
    return true;
  }

  /** @return {boolean} */
  function r_J() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    {
      var /** number */ v_2 = base.limit - base.cursor;
      lab0: {
        if (!base.eq_s_b("a")) {
          break lab0;
        }
        return false;
      }
      base.cursor = base.limit - v_2;
    }
    {
      var /** number */ v_3 = base.limit - base.cursor;
      lab1: {
        if (!base.eq_s_b("e")) {
          break lab1;
        }
        return false;
      }
      base.cursor = base.limit - v_3;
    }
    return true;
  }

  /** @return {boolean} */
  function r_K() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 3;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    lab0: {
      var /** number */ v_2 = base.limit - base.cursor;
      lab1: {
        if (!base.eq_s_b("l")) {
          break lab1;
        }
        break lab0;
      }
      base.cursor = base.limit - v_2;
      lab2: {
        if (!base.eq_s_b("i")) {
          break lab2;
        }
        break lab0;
      }
      base.cursor = base.limit - v_2;
      if (!base.eq_s_b("e")) {
        return false;
      }
      if (base.cursor <= base.limit_backward) {
        return false;
      }
      base.cursor--;
      if (!base.eq_s_b("u")) {
        return false;
      }
    }
    return true;
  }

  /** @return {boolean} */
  function r_L() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    {
      var /** number */ v_2 = base.limit - base.cursor;
      lab0: {
        if (!base.eq_s_b("u")) {
          break lab0;
        }
        return false;
      }
      base.cursor = base.limit - v_2;
    }
    {
      var /** number */ v_3 = base.limit - base.cursor;
      lab1: {
        if (!base.eq_s_b("x")) {
          break lab1;
        }
        return false;
      }
      base.cursor = base.limit - v_3;
    }
    {
      var /** number */ v_4 = base.limit - base.cursor;
      lab2: {
        if (!base.eq_s_b("s")) {
          break lab2;
        }
        {
          var /** number */ v_5 = base.limit - base.cursor;
          lab3: {
            if (!base.eq_s_b("o")) {
              break lab3;
            }
            break lab2;
          }
          base.cursor = base.limit - v_5;
        }
        return false;
      }
      base.cursor = base.limit - v_4;
    }
    return true;
  }

  /** @return {boolean} */
  function r_M() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    {
      var /** number */ v_2 = base.limit - base.cursor;
      lab0: {
        if (!base.eq_s_b("a")) {
          break lab0;
        }
        return false;
      }
      base.cursor = base.limit - v_2;
    }
    {
      var /** number */ v_3 = base.limit - base.cursor;
      lab1: {
        if (!base.eq_s_b("c")) {
          break lab1;
        }
        return false;
      }
      base.cursor = base.limit - v_3;
    }
    {
      var /** number */ v_4 = base.limit - base.cursor;
      lab2: {
        if (!base.eq_s_b("e")) {
          break lab2;
        }
        return false;
      }
      base.cursor = base.limit - v_4;
    }
    {
      var /** number */ v_5 = base.limit - base.cursor;
      lab3: {
        if (!base.eq_s_b("m")) {
          break lab3;
        }
        return false;
      }
      base.cursor = base.limit - v_5;
    }
    return true;
  }

  /** @return {boolean} */
  function r_N() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 3;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    {
      var /** number */ c2 = base.cursor - 2;
      if (c2 < base.limit_backward) {
        return false;
      }
      base.cursor = c2;
    }
    lab0: {
      var /** number */ v_2 = base.limit - base.cursor;
      lab1: {
        {
          var /** number */ v_3 = base.limit - base.cursor;
          lab2: {
            if (!base.eq_s_b("s")) {
              break lab2;
            }
            break lab1;
          }
          base.cursor = base.limit - v_3;
        }
        break lab0;
      }
      base.cursor = base.limit - v_2;
      {
        var /** number */ c3 = base.cursor - 2;
        if (c3 < base.limit_backward) {
          return false;
        }
        base.cursor = c3;
      }
    }
    return true;
  }

  /** @return {boolean} */
  function r_O() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    lab0: {
      var /** number */ v_2 = base.limit - base.cursor;
      lab1: {
        if (!base.eq_s_b("l")) {
          break lab1;
        }
        break lab0;
      }
      base.cursor = base.limit - v_2;
      if (!base.eq_s_b("i")) {
        return false;
      }
    }
    return true;
  }

  /** @return {boolean} */
  function r_P() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    {
      var /** number */ v_2 = base.limit - base.cursor;
      lab0: {
        if (!base.eq_s_b("c")) {
          break lab0;
        }
        return false;
      }
      base.cursor = base.limit - v_2;
    }
    return true;
  }

  /** @return {boolean} */
  function r_Q() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    var /** number */ v_2 = base.limit - base.cursor;
    {
      var /** number */ c2 = base.cursor - 3;
      if (c2 < base.limit_backward) {
        return false;
      }
      base.cursor = c2;
    }
    base.cursor = base.limit - v_2;
    {
      var /** number */ v_3 = base.limit - base.cursor;
      lab0: {
        if (!base.eq_s_b("l")) {
          break lab0;
        }
        return false;
      }
      base.cursor = base.limit - v_3;
    }
    {
      var /** number */ v_4 = base.limit - base.cursor;
      lab1: {
        if (!base.eq_s_b("n")) {
          break lab1;
        }
        return false;
      }
      base.cursor = base.limit - v_4;
    }
    return true;
  }

  /** @return {boolean} */
  function r_R() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    lab0: {
      var /** number */ v_2 = base.limit - base.cursor;
      lab1: {
        if (!base.eq_s_b("n")) {
          break lab1;
        }
        break lab0;
      }
      base.cursor = base.limit - v_2;
      if (!base.eq_s_b("r")) {
        return false;
      }
    }
    return true;
  }

  /** @return {boolean} */
  function r_S() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    lab0: {
      var /** number */ v_2 = base.limit - base.cursor;
      lab1: {
        if (!base.eq_s_b("dr")) {
          break lab1;
        }
        break lab0;
      }
      base.cursor = base.limit - v_2;
      if (!base.eq_s_b("t")) {
        return false;
      }
      {
        var /** number */ v_3 = base.limit - base.cursor;
        lab2: {
          if (!base.eq_s_b("t")) {
            break lab2;
          }
          return false;
        }
        base.cursor = base.limit - v_3;
      }
    }
    return true;
  }

  /** @return {boolean} */
  function r_T() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    lab0: {
      var /** number */ v_2 = base.limit - base.cursor;
      lab1: {
        if (!base.eq_s_b("s")) {
          break lab1;
        }
        break lab0;
      }
      base.cursor = base.limit - v_2;
      if (!base.eq_s_b("t")) {
        return false;
      }
      {
        var /** number */ v_3 = base.limit - base.cursor;
        lab2: {
          if (!base.eq_s_b("o")) {
            break lab2;
          }
          return false;
        }
        base.cursor = base.limit - v_3;
      }
    }
    return true;
  }

  /** @return {boolean} */
  function r_U() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    lab0: {
      var /** number */ v_2 = base.limit - base.cursor;
      lab1: {
        if (!base.eq_s_b("l")) {
          break lab1;
        }
        break lab0;
      }
      base.cursor = base.limit - v_2;
      lab2: {
        if (!base.eq_s_b("m")) {
          break lab2;
        }
        break lab0;
      }
      base.cursor = base.limit - v_2;
      lab3: {
        if (!base.eq_s_b("n")) {
          break lab3;
        }
        break lab0;
      }
      base.cursor = base.limit - v_2;
      if (!base.eq_s_b("r")) {
        return false;
      }
    }
    return true;
  }

  /** @return {boolean} */
  function r_V() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    if (!base.eq_s_b("c")) {
      return false;
    }
    return true;
  }

  /** @return {boolean} */
  function r_W() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    {
      var /** number */ v_2 = base.limit - base.cursor;
      lab0: {
        if (!base.eq_s_b("s")) {
          break lab0;
        }
        return false;
      }
      base.cursor = base.limit - v_2;
    }
    {
      var /** number */ v_3 = base.limit - base.cursor;
      lab1: {
        if (!base.eq_s_b("u")) {
          break lab1;
        }
        return false;
      }
      base.cursor = base.limit - v_3;
    }
    return true;
  }

  /** @return {boolean} */
  function r_X() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    lab0: {
      var /** number */ v_2 = base.limit - base.cursor;
      lab1: {
        if (!base.eq_s_b("l")) {
          break lab1;
        }
        break lab0;
      }
      base.cursor = base.limit - v_2;
      lab2: {
        if (!base.eq_s_b("i")) {
          break lab2;
        }
        break lab0;
      }
      base.cursor = base.limit - v_2;
      if (!base.eq_s_b("e")) {
        return false;
      }
      if (base.cursor <= base.limit_backward) {
        return false;
      }
      base.cursor--;
      if (!base.eq_s_b("u")) {
        return false;
      }
    }
    return true;
  }

  /** @return {boolean} */
  function r_Y() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    if (!base.eq_s_b("in")) {
      return false;
    }
    return true;
  }

  /** @return {boolean} */
  function r_Z() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    {
      var /** number */ v_2 = base.limit - base.cursor;
      lab0: {
        if (!base.eq_s_b("f")) {
          break lab0;
        }
        return false;
      }
      base.cursor = base.limit - v_2;
    }
    return true;
  }

  /** @return {boolean} */
  function r_AA() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    if (base.find_among_b(a_0) == 0) {
      return false;
    }
    return true;
  }

  /** @return {boolean} */
  function r_BB() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 3;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    {
      var /** number */ v_2 = base.limit - base.cursor;
      lab0: {
        if (!base.eq_s_b("met")) {
          break lab0;
        }
        return false;
      }
      base.cursor = base.limit - v_2;
    }
    {
      var /** number */ v_3 = base.limit - base.cursor;
      lab1: {
        if (!base.eq_s_b("ryst")) {
          break lab1;
        }
        return false;
      }
      base.cursor = base.limit - v_3;
    }
    return true;
  }

  /** @return {boolean} */
  function r_CC() {
    var /** number */ v_1 = base.limit - base.cursor;
    {
      var /** number */ c1 = base.cursor - 2;
      if (c1 < base.limit_backward) {
        return false;
      }
      base.cursor = c1;
    }
    base.cursor = base.limit - v_1;
    if (!base.eq_s_b("l")) {
      return false;
    }
    return true;
  }

  /** @return {boolean} */
  function r_endings() {
    base.ket = base.cursor;
    if (base.find_among_b(a_1) == 0) {
      return false;
    }
    base.bra = base.cursor;
    if (!base.slice_del()) {
      return false;
    }
    return true;
  }

  /** @return {boolean} */
  function r_undouble() {
    var /** number */ v_1 = base.limit - base.cursor;
    if (base.find_among_b(a_2) == 0) {
      return false;
    }
    base.cursor = base.limit - v_1;
    base.ket = base.cursor;
    if (base.cursor <= base.limit_backward) {
      return false;
    }
    base.cursor--;
    base.bra = base.cursor;
    if (!base.slice_del()) {
      return false;
    }
    return true;
  }

  /** @return {boolean} */
  function r_respell() {
    var /** number */ among_var;
    base.ket = base.cursor;
    among_var = base.find_among_b(a_3);
    if (among_var == 0) {
      return false;
    }
    base.bra = base.cursor;
    switch (among_var) {
      case 1:
        if (!base.slice_from("ief")) {
          return false;
        }
        break;
      case 2:
        if (!base.slice_from("uc")) {
          return false;
        }
        break;
      case 3:
        if (!base.slice_from("um")) {
          return false;
        }
        break;
      case 4:
        if (!base.slice_from("rb")) {
          return false;
        }
        break;
      case 5:
        if (!base.slice_from("ur")) {
          return false;
        }
        break;
      case 6:
        if (!base.slice_from("ister")) {
          return false;
        }
        break;
      case 7:
        if (!base.slice_from("meter")) {
          return false;
        }
        break;
      case 8:
        if (!base.slice_from("olut")) {
          return false;
        }
        break;
      case 9:
        {
          var /** number */ v_1 = base.limit - base.cursor;
          lab0: {
            if (!base.eq_s_b("a")) {
              break lab0;
            }
            return false;
          }
          base.cursor = base.limit - v_1;
        }
        {
          var /** number */ v_2 = base.limit - base.cursor;
          lab1: {
            if (!base.eq_s_b("i")) {
              break lab1;
            }
            return false;
          }
          base.cursor = base.limit - v_2;
        }
        {
          var /** number */ v_3 = base.limit - base.cursor;
          lab2: {
            if (!base.eq_s_b("o")) {
              break lab2;
            }
            return false;
          }
          base.cursor = base.limit - v_3;
        }
        if (!base.slice_from("l")) {
          return false;
        }
        break;
      case 10:
        if (!base.slice_from("bic")) {
          return false;
        }
        break;
      case 11:
        if (!base.slice_from("dic")) {
          return false;
        }
        break;
      case 12:
        if (!base.slice_from("pic")) {
          return false;
        }
        break;
      case 13:
        if (!base.slice_from("tic")) {
          return false;
        }
        break;
      case 14:
        if (!base.slice_from("ac")) {
          return false;
        }
        break;
      case 15:
        if (!base.slice_from("ec")) {
          return false;
        }
        break;
      case 16:
        if (!base.slice_from("ic")) {
          return false;
        }
        break;
      case 17:
        if (!base.slice_from("luc")) {
          return false;
        }
        break;
      case 18:
        if (!base.slice_from("uas")) {
          return false;
        }
        break;
      case 19:
        if (!base.slice_from("vas")) {
          return false;
        }
        break;
      case 20:
        if (!base.slice_from("cis")) {
          return false;
        }
        break;
      case 21:
        if (!base.slice_from("lis")) {
          return false;
        }
        break;
      case 22:
        if (!base.slice_from("eris")) {
          return false;
        }
        break;
      case 23:
        if (!base.slice_from("pans")) {
          return false;
        }
        break;
      case 24:
        {
          var /** number */ v_4 = base.limit - base.cursor;
          lab3: {
            if (!base.eq_s_b("s")) {
              break lab3;
            }
            return false;
          }
          base.cursor = base.limit - v_4;
        }
        if (!base.slice_from("ens")) {
          return false;
        }
        break;
      case 25:
        if (!base.slice_from("ons")) {
          return false;
        }
        break;
      case 26:
        if (!base.slice_from("lus")) {
          return false;
        }
        break;
      case 27:
        if (!base.slice_from("rus")) {
          return false;
        }
        break;
      case 28:
        {
          var /** number */ v_5 = base.limit - base.cursor;
          lab4: {
            if (!base.eq_s_b("p")) {
              break lab4;
            }
            return false;
          }
          base.cursor = base.limit - v_5;
        }
        {
          var /** number */ v_6 = base.limit - base.cursor;
          lab5: {
            if (!base.eq_s_b("t")) {
              break lab5;
            }
            return false;
          }
          base.cursor = base.limit - v_6;
        }
        if (!base.slice_from("hes")) {
          return false;
        }
        break;
      case 29:
        if (!base.slice_from("mis")) {
          return false;
        }
        break;
      case 30:
        {
          var /** number */ v_7 = base.limit - base.cursor;
          lab6: {
            if (!base.eq_s_b("m")) {
              break lab6;
            }
            return false;
          }
          base.cursor = base.limit - v_7;
        }
        if (!base.slice_from("ens")) {
          return false;
        }
        break;
      case 31:
        if (!base.slice_from("ers")) {
          return false;
        }
        break;
      case 32:
        {
          var /** number */ v_8 = base.limit - base.cursor;
          lab7: {
            if (!base.eq_s_b("n")) {
              break lab7;
            }
            return false;
          }
          base.cursor = base.limit - v_8;
        }
        if (!base.slice_from("es")) {
          return false;
        }
        break;
      case 33:
        if (!base.slice_from("ys")) {
          return false;
        }
        break;
    }
    return true;
  }

  this.stem = /** @return {boolean} */ function () {
    base.limit_backward = base.cursor;
    base.cursor = base.limit;
    var /** number */ v_1 = base.limit - base.cursor;
    r_endings();
    base.cursor = base.limit - v_1;
    var /** number */ v_2 = base.limit - base.cursor;
    r_undouble();
    base.cursor = base.limit - v_2;
    var /** number */ v_3 = base.limit - base.cursor;
    r_respell();
    base.cursor = base.limit - v_3;
    base.cursor = base.limit_backward;
    return true;
  };

  /**@return{string}*/
  this["stemWord"] = function (/**string*/ word) {
    base.setCurrent(word);
    this.stem();
    return base.getCurrent();
  };
};
